(**
  A type-only declaration module.  This module is intended to be re-exported
  from the Pds_reachability_logger_utils module interface and implementation; it
  should not be used directly.
*)

(**
  The logging levels available for PDS reachability graphs.
*)
type pds_reachability_logger_level =
  | Pds_reachability_log_each_edge
    (** Logs the addition of each and every edge to the PDS reachability
        analysis  This includes all edges created by edge generation
        functions. *)
  | Pds_reachability_log_each_call
    (** Logs the PDS generated by each external call to the reachability
        analysis module. *)
  | Pds_reachability_log_nothing
    (** Does not log PDS reachability graphs. *)
  [@@deriving ord]
;;

let pp_pds_reachability_logger_level level =
  match level with
  | Pds_reachability_log_each_edge -> "each-edge"
  | Pds_reachability_log_each_call -> "each-call"
  | Pds_reachability_log_nothing -> "nothing"
;;

(**
  The names given to PDS reachability graphs.  Each logger name consists of a
  prefix (expected to uniquely name the reachability analysis), a major update
  index, and a minor update index.
*)
type pds_reachability_logger_name =
  | Pds_reachability_logger_name of string * int * int
;;
